import { Router } from 'express'
import { v4 as uuidv4 } from 'uuid'
import { connectToMongo } from '../db.js'
import { hashPwd, asyncRoute } from '../helpers.js'
import { IMAGEKIT_URL, SEED_SECRET } from '../config.js'

const router = Router()

router.all('/seed', asyncRoute(async (req, res, ok, err) => {
  const db = await connectToMongo()
  if (SEED_SECRET) {
    const reqSecret = req.headers['x-seed-secret'] || req.query.secret
    if (reqSecret !== SEED_SECRET) return err('Unauthorized', 401)
  }

  await db.collection('items').deleteMany({})
  await db.collection('rent_items').deleteMany({})
  await db.collection('decoration_kits').deleteMany({})

  const citiesExist = await db.collection('allowed_cities').countDocuments({})
  if (citiesExist === 0) {
    await db.collection('allowed_cities').insertMany([
      { id: uuidv4(), name: 'Ranchi', state: 'Jharkhand', active: true, created_at: new Date() },
      { id: uuidv4(), name: 'Pune',   state: 'Maharashtra', active: true, created_at: new Date() },
    ])
  }

  const IK = IMAGEKIT_URL
  const items = [
    { name: 'Mix Balloon Set',               category: 'Balloons',         type_finish: 'Mix',          size: '10-12 inch', unit_cost: 16,   selling_price_unit: 20.8,  stock_count: 500, tags: ['birthday','party','celebration','universal'],           image_url: IK+'/dataset/3-5k/balloons_mix.jpg' },
    { name: 'Transparent Confetti Balloon',  category: 'Balloons',         type_finish: 'Transparent',  size: '10-12 inch', unit_cost: 25,   selling_price_unit: 32.5,  stock_count: 200, tags: ['birthday','party','celebration','universal'],           image_url: IK+'/dataset/3-5k/balloons_confetti.jpg' },
    { name: 'Pink Balloon',                  category: 'Balloons',         type_finish: 'Coloured',     size: '10-12 inch', unit_cost: 8,    selling_price_unit: 10.4,  stock_count: 500, tags: ['birthday','baby_shower','party','universal'],           image_url: IK+'/dataset/3-5k/balloons_pink.jpg' },
    { name: 'Red Balloon',                   category: 'Balloons',         type_finish: 'Coloured',     size: '10-12 inch', unit_cost: 9,    selling_price_unit: 11.7,  stock_count: 500, tags: ['anniversary','party','universal','romantic'],           image_url: IK+'/dataset/3-5k/balloons_red.jpg' },
    { name: 'Golden Chrome Balloon',         category: 'Balloons',         type_finish: 'Chrome',       size: '12 inch',    unit_cost: 12,   selling_price_unit: 15.6,  stock_count: 250, tags: ['birthday','anniversary','wedding','celebration'],       image_url: IK+'/dataset/3-5k/balloons_chrome_gold.jpg' },
    { name: 'Rose Gold Balloon',             category: 'Balloons',         type_finish: 'Chrome',       size: '12 inch',    unit_cost: 12,   selling_price_unit: 15.6,  stock_count: 250, tags: ['birthday','engagement','anniversary','celebration'],    image_url: IK+'/dataset/3-5k/balloons_rose_gold.jpg' },
    { name: 'Pastel Balloon Small',          category: 'Balloons',         type_finish: 'Pastel',       size: '10-12 inch', unit_cost: 14,   selling_price_unit: 18.2,  stock_count: 500, tags: ['birthday','baby_shower','party','universal'],           image_url: IK+'/dataset/3-5k/balloons_pastel.jpg' },
    { name: 'Red Heart Balloon',             category: 'Balloons',         type_finish: 'Foil Shape',   size: '12 inch',    unit_cost: 60,   selling_price_unit: 78,    stock_count: 100, tags: ['anniversary','romantic','engagement','valentine'],      image_url: IK+'/dataset/3-5k/balloons_heart_red.jpg' },
    { name: 'Transparent Balloon Large',     category: 'Balloons',         type_finish: 'Transparent',  size: '20 inch',    unit_cost: 60,   selling_price_unit: 78,    stock_count: 100, tags: ['birthday','party','universal'],                         image_url: IK+'/dataset/3-5k/balloons_transparent_large.jpg' },
    { name: 'Foil Backdrop Curtain',         category: 'Backdrop',         type_finish: 'Foil',         size: '6ft x 4ft',  unit_cost: 350,  selling_price_unit: 455,   stock_count: 20,  tags: ['birthday','anniversary','party','celebration','universal'], image_url: IK+'/dataset/3-5k/backdrop_foil.jpg' },
    { name: 'Net Backdrop Large',            category: 'Backdrop',         type_finish: 'Net',          size: '5m x 1.5m',  unit_cost: 500,  selling_price_unit: 650,   stock_count: 20,  tags: ['birthday','anniversary','wedding','party','universal'],  image_url: IK+'/dataset/3-5k/backdrop_net.jpg' },
    { name: 'LED Curtain String',            category: 'Lighting',         type_finish: 'LED Curtain',  size: 'Standard',   unit_cost: 755,  selling_price_unit: 981.5, stock_count: 15,  tags: ['anniversary','romantic','wedding','dinner','universal'],image_url: IK+'/dataset/3-5k/lights_curtain.jpg' },
    { name: 'Artificial Flower Set',         category: 'Floral',           type_finish: 'Artificial',   size: 'Standard',   unit_cost: 1200, selling_price_unit: 1560,  stock_count: 10,  tags: ['wedding','anniversary','romantic','celebration'],       image_url: IK+'/dataset/5-10k/flower_wall.jpg' },
    { name: 'Neon Sign - Happy Birthday',    category: 'Neon Signs',       type_finish: 'Neon',         size: 'N/A',        unit_cost: 2000, selling_price_unit: 2600,  stock_count: 5,   tags: ['birthday','celebration','party'],                       image_url: IK+'/dataset/5-10k/neon_custom.jpg' },
    { name: "Neon Sign - Let's Party (Pink)",category: 'Neon Signs',       type_finish: 'Neon',         size: 'Medium',     unit_cost: 2000, selling_price_unit: 2600,  stock_count: 5,   tags: ['birthday','party','celebration'],                       image_url: IK+'/dataset/5-10k/neon_dance.jpg' },
    { name: 'Neon Sign - Good Vibes Only',   category: 'Neon Signs',       type_finish: 'Neon',         size: 'N/A',        unit_cost: 2300, selling_price_unit: 2990,  stock_count: 5,   tags: ['party','celebration','birthday'],                       image_url: IK+'/dataset/5-10k/neon_sign.jpg' },
    { name: 'Neon Sign - Bride To Be',       category: 'Neon Signs',       type_finish: 'Neon',         size: 'N/A',        unit_cost: 2000, selling_price_unit: 2600,  stock_count: 5,   tags: ['wedding','engagement','bride_shower'],                  image_url: IK+'/dataset/5-10k/neon_custom.jpg' },
    { name: 'Foil Number Balloon',           category: 'Foil Balloons',    type_finish: 'Foil',         size: '16 inch',    unit_cost: 150,  selling_price_unit: 195,   stock_count: 100, tags: ['birthday','anniversary','celebration'],                 image_url: IK+'/dataset/5-10k/marquee_letters.jpg' },
    { name: 'Foil Letter Balloon',           category: 'Foil Balloons',    type_finish: 'Foil',         size: '32 inch',    unit_cost: 200,  selling_price_unit: 260,   stock_count: 100, tags: ['birthday','anniversary','celebration'],                 image_url: IK+'/dataset/5-10k/marquee_letters.jpg' },
    { name: 'LED Pillar Candle Set (3 pcs)', category: 'Lighting',         type_finish: 'LED',          size: 'Set of 3',   unit_cost: 400,  selling_price_unit: 520,   stock_count: 10,  tags: ['anniversary','romantic','dinner','wedding'],            image_url: IK+'/dataset/5-10k/centerpiece.jpg' },
    { name: 'Colour Net Curtain',            category: 'Backdrop',         type_finish: 'Net',          size: '8ft x 4ft',  unit_cost: 400,  selling_price_unit: 520,   stock_count: 20,  tags: ['haldi','festival','wedding','celebration'],             image_url: IK+'/dataset/3-5k/backdrop_net.jpg' },
    { name: 'Glue Dot Roll (Balloon)',       category: 'Tools & Supplies', type_finish: 'Adhesive',     size: 'Roll',       unit_cost: 250,  selling_price_unit: 325,   stock_count: 50,  tags: ['universal'], image_url: '' },
    { name: 'Ribbon Roll',                   category: 'Tools & Supplies', type_finish: 'Ribbon',       size: 'Standard',   unit_cost: 100,  selling_price_unit: 130,   stock_count: 50,  tags: ['universal'], image_url: '' },
    { name: 'Tape Roll',                     category: 'Tools & Supplies', type_finish: 'Tape',         size: 'Standard',   unit_cost: 50,   selling_price_unit: 65,    stock_count: 100, tags: ['universal'], image_url: '' },
    { name: 'Fishing String Roll',           category: 'Tools & Supplies', type_finish: 'Thread/String',size: 'Small roll', unit_cost: 400,  selling_price_unit: 520,   stock_count: 50,  tags: ['universal'], image_url: '' },
    { name: 'Zip Tie Packet',                category: 'Tools & Supplies', type_finish: 'Fasteners',    size: 'N/A',        unit_cost: 500,  selling_price_unit: 650,   stock_count: 50,  tags: ['universal'], image_url: '' },
  ].map(i => ({ ...i, id: uuidv4(), price: i.selling_price_unit, active: true, created_at: new Date() }))
  await db.collection('items').insertMany(items)

  const rentItems = [
    { item_id: 'HV-0001', name: 'Happy Birthday Neon Sign LED 12x18 Inch',         category: 'Lighting', rental_cost: 500, selling_price: 2600, is_sellable: true,  image_url: IK+'/rentals/neon_hb.jpg' },
    { item_id: 'HV-0002', name: "Let's Party LED Neon (15x10x1 cm)",               category: 'Lighting', rental_cost: 275, selling_price: 1430, is_sellable: true,  image_url: IK+'/rentals/neon_lp.jpg' },
    { item_id: 'HV-0007', name: 'Alphabet LED Marquee Letter (Warm White)',         category: 'Lighting', rental_cost: 75,  selling_price: 390,  is_sellable: true,  image_url: IK+'/rentals/marquee_letter.jpg' },
    { item_id: 'HV-0011', name: 'Background Support Kit Metal Stand 9ft x 9ft',    category: 'Stands',   rental_cost: 625, selling_price: null, is_sellable: false, image_url: IK+'/rentals/stand_metal.jpg' },
    { item_id: 'HV-0013', name: 'Rectangle Balloon Stand (PVC) 190x210cm',         category: 'Stands',   rental_cost: 300, selling_price: null, is_sellable: false, image_url: IK+'/rentals/stand_rect.jpg' },
    { item_id: 'HV-0014', name: 'Round Arch Balloon Stand (PVC) 5ft x 6ft',        category: 'Stands',   rental_cost: 375, selling_price: null, is_sellable: false, image_url: IK+'/rentals/stand_arch.jpg' },
    { item_id: 'HV-0020', name: 'Acrylic Glass Flameless LED Candles (Pack of 3)', category: 'Lighting', rental_cost: 300, selling_price: 1560, is_sellable: true,  image_url: IK+'/rentals/candles_acrylic.jpg' },
    { item_id: 'HV-0026', name: 'Artificial Silk Rose Petals (Red, 500 pcs)',       category: 'Floral',   rental_cost: 75,  selling_price: 390,  is_sellable: true,  image_url: IK+'/rentals/petals_rose.jpg' },
    { item_id: 'HV-0032', name: 'Marigold Garlands (Pack of 10)',                  category: 'Floral',   rental_cost: 125, selling_price: 650,  is_sellable: true,  image_url: IK+'/rentals/marigold.jpg' },
  ].map(i => ({ ...i, id: uuidv4(), qty_available: 1, active: true, created_at: new Date() }))
  await db.collection('rent_items').insertMany(rentItems)

  const kitsToInsert = [
    { kit_code:'KTS-001', name:'Boss Baby Blast (KTS-001)',           occasion_tags:['birthday','party','boss baby'],          selling_total:8905,  purchase_total:6850,  bom:[{"item":"Latex Balloons (Mix palette)","qty":300,"uom":"pcs","unit_purchase":16},{"item":"Foil Backdrop Curtain Silver","qty":1,"uom":"set","unit_purchase":350},{"item":"Foil Number Balloon","qty":1,"uom":"pc","unit_purchase":400},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Boss Baby', audience:'Kids' },
    { kit_code:'KTS-002', name:'Cars Speed Track (KTS-002)',           occasion_tags:['birthday','party','cars'],               selling_total:5590,  purchase_total:4300,  bom:[{"item":"Latex Balloons (Red palette)","qty":250,"uom":"pcs","unit_purchase":9},{"item":"Foil Backdrop Curtain Red","qty":1,"uom":"set","unit_purchase":350},{"item":"Foil Number Balloon","qty":1,"uom":"pc","unit_purchase":400},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Cars', audience:'Kids' },
    { kit_code:'KTS-003', name:'Cocomelon Garden Pop (KTS-003)',       occasion_tags:['birthday','party','cocomelon'],          selling_total:8905,  purchase_total:6850,  bom:[{"item":"Latex Balloons (Mix palette)","qty":300,"uom":"pcs","unit_purchase":16},{"item":"Foil Backdrop Curtain Silver","qty":1,"uom":"set","unit_purchase":350},{"item":"Foil Number Balloon","qty":1,"uom":"pc","unit_purchase":400},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Cocomelon', audience:'Kids' },
    { kit_code:'KTS-004', name:'Disney Princess Silver Gala (KTS-004)',occasion_tags:['birthday','party','disney princess'],   selling_total:10985, purchase_total:8450,  bom:[{"item":"Latex Balloons (Mix palette)","qty":400,"uom":"pcs","unit_purchase":16},{"item":"Foil Backdrop Curtain Silver","qty":1,"uom":"set","unit_purchase":350},{"item":"Foil Number Balloon","qty":1,"uom":"pc","unit_purchase":400},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Disney Princess', audience:'Kids, Girls' },
    { kit_code:'KTS-012', name:'Unicorn Sparkle Pastels (KTS-012)',    occasion_tags:['birthday','party','unicorn'],            selling_total:10595, purchase_total:8150,  bom:[{"item":"Latex Balloons (Pastel palette)","qty":400,"uom":"pcs","unit_purchase":14},{"item":"Net Backdrop White","qty":1,"uom":"set","unit_purchase":500},{"item":"Foil Backdrop Curtain Silver","qty":1,"uom":"set","unit_purchase":350},{"item":"Foil Number Balloon","qty":1,"uom":"pc","unit_purchase":400},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Unicorn', audience:'Kids, Girls' },
    { kit_code:'KTS-013', name:'Newborn Naming Ceremony (KTS-013)',    occasion_tags:['ceremony','baby_shower','naming ceremony'],selling_total:6500, purchase_total:5000,  bom:[{"item":"Latex Balloons (Mix palette)","qty":200,"uom":"pcs","unit_purchase":16},{"item":"Net Backdrop White","qty":1,"uom":"set","unit_purchase":500},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Naming Ceremony', audience:'Newborn' },
    { kit_code:'KTS-018', name:'Candle Light Dinner Luxe (KTS-018)',   occasion_tags:['anniversary','romantic','valentine','dinner'],selling_total:10660,purchase_total:8200,bom:[{"item":"Fresh Roses","qty":50,"uom":"pcs","unit_purchase":50},{"item":"LED Pillar Candles Set of 3","qty":1,"uom":"set","unit_purchase":1200},{"item":"Batteries for LED candles","qty":1,"uom":"set","unit_purchase":200},{"item":"Neon Light Good Vibes Only","qty":1,"uom":"pc","unit_purchase":2300},{"item":"Red Heart Balloons 12 inch","qty":25,"uom":"pcs","unit_purchase":60},{"item":"Net Backdrop","qty":1,"uom":"set","unit_purchase":500}], theme:'Candle Light Dinner', audience:'Couple' },
    { kit_code:'KTS-019', name:'Romantic Room Decor (KTS-019)',         occasion_tags:['anniversary','romantic','valentine'],    selling_total:13787, purchase_total:10605, bom:[{"item":"Latex Balloons Mix palette","qty":400,"uom":"pcs","unit_purchase":16},{"item":"White Net 3 pc set","qty":1,"uom":"set","unit_purchase":355},{"item":"Foil Letters I LOVE YOU 16 inch","qty":7,"uom":"pcs","unit_purchase":150},{"item":"Red Heart Balloons 12 inch","qty":25,"uom":"pcs","unit_purchase":60},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Romantic Room', audience:'Couple' },
    { kit_code:'KTS-020', name:'Canopy Decor Premium (KTS-020)',        occasion_tags:['anniversary','romantic','wedding'],      selling_total:8983,  purchase_total:6910,  bom:[{"item":"Latex Balloons Mix palette","qty":100,"uom":"pcs","unit_purchase":16},{"item":"White Net 3 pc set","qty":5,"uom":"sets","unit_purchase":355},{"item":"LED Curtain String","qty":1,"uom":"set","unit_purchase":755},{"item":"LED Pillar Candles Set of 3","qty":1,"uom":"set","unit_purchase":1200},{"item":"Batteries for LED candles","qty":1,"uom":"set","unit_purchase":200},{"item":"Red Latex Balloons","qty":20,"uom":"pcs","unit_purchase":9},{"item":"Red Heart Balloons 12 inch","qty":20,"uom":"pcs","unit_purchase":60}], theme:'Canopy', audience:'Couple' },
    { kit_code:'KTS-022', name:'Anniversary Classic Net (KTS-022)',     occasion_tags:['anniversary','romantic'],                selling_total:9412,  purchase_total:7240,  bom:[{"item":"Latex Balloons Mix palette","qty":340,"uom":"pcs","unit_purchase":16},{"item":"Net Backdrop Large","qty":1,"uom":"set","unit_purchase":500},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Anniversary', audience:'Couple' },
    { kit_code:'KTS-023', name:'Haldi Celebration Bloom (KTS-023)',     occasion_tags:['haldi','wedding','festival'],            selling_total:12162, purchase_total:9355,  bom:[{"item":"Latex Balloons Mix palette","qty":400,"uom":"pcs","unit_purchase":16},{"item":"Colour Net Curtain 8ft x 4ft","qty":1,"uom":"set","unit_purchase":400},{"item":"Net Backdrop Large","qty":1,"uom":"set","unit_purchase":500},{"item":"LED Curtain String","qty":1,"uom":"set","unit_purchase":755},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Haldi', audience:'Family' },
    { kit_code:'KTS-024', name:'Proposal Net & Roses (KTS-024)',        occasion_tags:['engagement','anniversary','proposal'],   selling_total:14177, purchase_total:10905, bom:[{"item":"Latex Balloons Mix palette","qty":300,"uom":"pcs","unit_purchase":16},{"item":"Fresh Roses","qty":50,"uom":"pcs","unit_purchase":50},{"item":"Net Backdrop Large","qty":1,"uom":"set","unit_purchase":500},{"item":"Foil Letters I LOVE YOU 16 inch","qty":7,"uom":"pcs","unit_purchase":150},{"item":"LED Curtain String","qty":1,"uom":"set","unit_purchase":755},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Proposal', audience:'Couple' },
    { kit_code:'KTS-025', name:'Bride To Be Glow (KTS-025)',            occasion_tags:['wedding','engagement','bride shower'],   selling_total:10082, purchase_total:7755,  bom:[{"item":"Latex Balloons Pink palette","qty":400,"uom":"pcs","unit_purchase":8},{"item":"Neon Light Bride To Be","qty":1,"uom":"pc","unit_purchase":2000},{"item":"Net Backdrop Large","qty":1,"uom":"set","unit_purchase":500},{"item":"LED Curtain String","qty":1,"uom":"set","unit_purchase":755},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Bride To Be', audience:'Bride' },
    { kit_code:'KTS-026', name:'Holi Color Blast (KTS-026)',            occasion_tags:['festival','holi','party'],               selling_total:5850,  purchase_total:4500,  bom:[{"item":"Latex Balloons Mix palette","qty":200,"uom":"pcs","unit_purchase":16},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Holi', audience:'Friends, Family' },
    { kit_code:'KTS-027', name:'Neon Party Starburst (KTS-027)',        occasion_tags:['birthday','party','neon'],               selling_total:14560, purchase_total:11200, bom:[{"item":"Latex Balloons Mix palette","qty":400,"uom":"pcs","unit_purchase":16},{"item":"Net Backdrop Large","qty":1,"uom":"set","unit_purchase":500},{"item":"Star Foil Balloons","qty":6,"uom":"pcs","unit_purchase":500},{"item":"Glue Dots","qty":1,"uom":"pc","unit_purchase":250},{"item":"Tape","qty":1,"uom":"pc","unit_purchase":50},{"item":"Ribbon Roll","qty":1,"uom":"pc","unit_purchase":100},{"item":"Fishing String Roll","qty":1,"uom":"pc","unit_purchase":400},{"item":"Zip Tie Packet","qty":1,"uom":"pc","unit_purchase":500}], theme:'Neon Party', audience:'Any' },
  ].map(k => ({ ...k, id: uuidv4(), room_types: ['Living Room','Hall','Bedroom'], kit_items: [], reference_images: [], labor_cost: 500, travel_cost: 500, total_items_cost: k.purchase_total, final_price: k.selling_total, setup_time_minutes: 60, difficulty: k.selling_total > 12000 ? 'hard' : k.selling_total > 8000 ? 'medium' : 'easy', color_theme: '', is_active: true, active: true, notes: '', description: k.theme + ' themed decoration for ' + k.audience, created_at: new Date(), updated_at: new Date() }))
  await db.collection('decoration_kits').insertMany(kitsToInsert)

  const dpData = [
    { name: 'Rahul Kumar',  phone: '9876543210', lat: 18.5204, lng: 73.8567, rating: 4.8, total_deliveries: 156 },
    { name: 'Priya Sharma', phone: '9876543211', lat: 18.5304, lng: 73.8467, rating: 4.9, total_deliveries: 203 },
    { name: 'Amit Singh',   phone: '9876543212', lat: 18.5104, lng: 73.8667, rating: 4.7, total_deliveries: 89  },
    { name: 'Neha Patel',   phone: '9876543213', lat: 18.5404, lng: 73.8367, rating: 4.6, total_deliveries: 124 },
  ]
  let dpCount = 0
  for (const dp of dpData) {
    const exists = await db.collection('delivery_persons').findOne({ phone: dp.phone })
    if (!exists) {
      await db.collection('delivery_persons').insertOne({ id: uuidv4(), name: dp.name, phone: dp.phone, password: hashPwd('1234'), is_active: true, current_location: { lat: dp.lat, lng: dp.lng, updated_at: new Date() }, schedule: {}, rating: dp.rating, total_deliveries: dp.total_deliveries, created_at: new Date() })
      dpCount++
    }
  }
  const deliveryPersons = await db.collection('delivery_persons').find({}).toArray()

  const adminExists = await db.collection('users').findOne({ email: 'admin@fatafatdecor.com' })
  if (!adminExists) {
    await db.collection('users').insertOne({ id: uuidv4(), name: 'Admin', email: 'admin@fatafatdecor.com', phone: '9999999999', password: hashPwd('admin123'), role: 'admin', credits: 999, has_purchased_credits: true, location: null, auth_provider: 'email', created_at: new Date() })
  }

  return ok({ success: true, items_count: items.length, rent_items_count: rentItems.length, kits_count: kitsToInsert.length, delivery_persons_count: deliveryPersons.length, message: 'Database seeded!' })
}))

export default router
